apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-demo-springboot
  template:
    metadata:
      labels:
        app: eks-demo-springboot
    spec:
      containers:
        - name: springboot
          image: ranendasdocker/eks-demo:eks-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: eks-demo-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jeks-demohooq-springboot